"""Initial migration

Revision ID: 5e1a7a6e1e61
Revises: 
Create Date: 2024-12-02 23:54:13.502010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1a7a6e1e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('regulator_name', sa.String(length=100), nullable=False),
    sa.Column('method_of_communication', sa.String(length=100), nullable=False),
    sa.Column('business_process_status', sa.String(length=50), nullable=False),
    sa.Column('affected_business_process', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circular')
    # ### end Alembic commands ###
